DavLockDB /tmp/DavLock

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html

    Include /data/config/apache-shares.conf
    ErrorLog /var/log/apache2/webdav-error.log
    CustomLog /var/log/apache2/webdav-access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName localhost
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile /data/config/ssl/server.crt
    SSLCertificateKeyFile /data/config/ssl/server.key

    Include /data/config/apache-shares.conf
    ErrorLog /var/log/apache2/webdav-ssl-error.log
    CustomLog /var/log/apache2/webdav-ssl-access.log combined
</VirtualHost>
